{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.gateway.enabled (eq .Values.gateway.implementation "gateway-api") .Values.gateway.listenerSet.enabled .Values.gateway.listenerSet.listeners -}}
{{- $apiVersion := include "st-common.capabilities.networkingGatewayListenerSet.apiVersion" . -}}
{{- if not (eq $apiVersion "false") -}}
apiVersion: {{ $apiVersion }}
kind: {{ ternary "XListenerSet" "ListenerSet" (eq $apiVersion "gateway.networking.x-k8s.io/v1alpha1") }}
metadata:
  name: {{ include "st-common.names.fullname" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  parentRef:
    {{- if .Values.gateway.listenerSet.parentRef }}
    {{- include "st-common.tplvalues.render" (dict "value" .Values.gateway.listenerSet.parentRef "context" $) | nindent 4 }}
    {{- else }}
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ include "st-common.gateway.fullname" . }}
    namespace: {{ include "st-common.gateway.namespace" . }}
    {{- end }}
  listeners: {{- include "st-common.tplvalues.render" (dict "value" .Values.gateway.listenerSet.listeners "context" $) | nindent 4 }}
{{- end -}}
{{- end -}}
