annotations:
  licenses: Apache-2.0
  images: |
    - name: netbox
      image: docker.io/netboxcommunity/netbox:v3.7.8-2.8.0
apiVersion: v2
appVersion: v3.7.8
dependencies:
- name: postgresql
  version: 18.7.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
- name: redis
  version: 27.0.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
- name: st-common
  repository: oci://ghcr.io/startechnica/charts
  version: 0.1.21
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
home: https://github.com/startechnica/apps/tree/main/charts/netbox
icon: https://raw.githubusercontent.com/netbox-community/netbox/develop/docs/netbox_logo.png
keywords:
  - ipam
  - netbox
kubeVersion: ">=1.25.0"
maintainers:
  - name: firmansyahn
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: netbox
type: application
version: 5.1.0
