{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if include "freeradius.tls.createSecret" . }}
{{- include "freeradius.tls.ca.init" . }}
{{- $ca := index $ "_freeradiusTlsCa" }}
{{- $releaseNamespace := include "st-common.names.namespace" . }}
{{- $clusterDomain := .Values.clusterDomain }}
{{- $fullname := include "st-common.names.fullname" . }}
{{- $altNames := list (printf "*.%s.%s.svc.%s" $fullname $releaseNamespace $clusterDomain) (printf "%s.%s.svc" $fullname $releaseNamespace) (printf "%s.%s" $fullname $releaseNamespace) $fullname -}}
{{- if .Values.gateway.hostnames }}
{{- $altNames = concat $altNames .Values.gateway.hostnames }}
{{- end }}
{{- $primaryHost := default $fullname (first .Values.gateway.hostnames) }}
{{- $crt := genSignedCert $primaryHost nil $altNames 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freeradius.tls.secretName" . }}
  namespace: {{ $releaseNamespace | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $crt.Cert | b64enc | quote }}
  tls.key: {{ $crt.Key | b64enc | quote }}
{{- end }}
