{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "external-service.fullname" . }}
  namespace: {{ include "external-service.namespace" . | quote }}
  labels: {{- include "external-service.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "external-service.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "external-service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "external-service.serviceAccountName" . }}
    namespace: {{ include "external-service.namespace" . | quote }}
{{- end }}