{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "external-service.fullname" . }}
  namespace: {{ include "external-service.namespace" . | quote }}
  labels: {{- include "external-service.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "external-service.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
rules:
  {{- if .Values.rbac.rules }}
  {{- include "external-service.tplvalues.render" (dict "value" .Values.rbac.rules "context" $) | nindent 2 }}
  {{- end }}
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
{{- end }}