{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "external-service.serviceAccountName" . }}
  namespace: {{ include "external-service.namespace" . | quote }}
  labels: {{- include "external-service.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.serviceAccount.annotations }}
  {{- $annotations := include "external-service.tplvalues.merge" ( dict "values" (list .Values.serviceAccount.annotations .Values.commonAnnotations ) "context" .) }}
  annotations: {{- include "external-service.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
