{{- /*
 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.envvarsSecret.enabled (not .Values.envvarsSecret.existingSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "st-common.names.envvars" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
stringData:
  {{- if not (empty .Values.envvarsSecret.extraConfigs) }}
  {{- include "st-common.tplvalues.render" ( dict "value" .Values.envvarsSecret.extraSecrets "context" $ ) | nindent 2 }}
  {{- end }}

{{- end -}}
