{{- if and .Values.gateway.enabled .Values.gateway.gatewayApi.create -}}
{{- if not (eq (include "common.capabilities.networkingGateway.apiVersion" .) "false") -}}
apiVersion: {{ include "common.capabilities.networkingGateway.apiVersion" . }}
kind: HTTPRoute
metadata:
  name: {{ include "netbox.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: netbox
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingress.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ default "ingressgateway" .Values.gateway.name | quote }}
    namespace: {{ default "istio-ingress" .Values.gateway.namespace | quote }}
  hostnames:
    - {{ .Values.ingress.hostname }}
    {{- range $host := $.Values.ingress.extraHosts }}
    - {{ $host.name | quote }}
    {{- end }}
  rules:
    {{- if not (empty .Values.ingress.path) }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ default "/" .Values.ingress.path | quote }}
      backendRefs:
        - name: {{ include "netbox.fullname" . }}
          port: {{ .Values.service.ports.http | int }}
    {{- end }}
    {{- range .Values.ingress.extraPaths }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path | quote }}
      backendRefs:
        - name: {{ .backend.serviceName | quote }}
          port: {{ .backend.servicePort | int }}
          kind: Service
    {{- end }}
{{- end -}}
{{- end -}}
