{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.reportsPersistence.enabled (not .Values.reportsPersistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "netbox.reports.pvcName" . }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: netbox
  {{- if or .Values.reportsPersistence.annotations .Values.commonAnnotations }}
  {{- $annotations := include "st-common.tplvalues.merge" ( dict "values" ( list .Values.reportsPersistence.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.reportsPersistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.reportsPersistence.size | quote }}
  {{- if .Values.reportsPersistence.selector }}
  selector: {{- include "st-common.tplvalues.render" (dict "value" .Values.reportsPersistence.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.reportsPersistence.dataSource }}
  dataSource: {{- include "st-common.tplvalues.render" (dict "value" .Values.reportsPersistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- include "st-common.storage.class" (dict "persistence" .Values.reportsPersistence "global" .Values.global) | nindent 2 }}
{{- end -}}
