{{ if and (or (.Files.Glob "files/daemon-config.json") .Values.daemonConfig) (not .Values.daemonConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-daemon-config
  namespace: {{ include "multus-cni.namespace" . | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
data:
{{- if (.Files.Glob "files/daemon-config.json") }}
  {{ (.Files.Glob "files/daemon-config.json").AsConfig | indent 2 }}
{{- else if .Values.daemonConfig }}
  daemon-config.json: |-
{{ .Values.daemonConfig | indent 4 }}
{{- end }}
{{- end }}