fullnameOverride: adminer

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/worker
          operator: Exists

service:
  ipFamilyPolicy: PreferDualStack

gateway:
  enabled: true
  gateway:
    name: webapps
    namespace: istio-ingress
  hostnames:
    - adminer.dxm.nainggolan.id
    - macam.macam.com
    - macam.macam.id
  tls:
    enabled: true
    selfSigned: true

  listenerSet:
    enabled: true

tls:
  enabled: true

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
