{{- /*
Copyright (c) 2025 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- range $gateway := .Values.gateways }}
{{- if and .enabled $.Values.serviceAccount.create (and .serviceAccount .serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .serviceAccount.automountServiceAccountToken | default true }}
metadata:
  name: {{ include "gateways.rbac.serviceAccountName" (dict "gatewayValues" $gateway "context" $) }}
  namespace: {{ include "st-common.names.namespace" $ | quote }}
  {{- $labels := include "st-common.tplvalues.merge" (dict "values" (list $.Values.commonLabels) "context" $) }}
  labels: {{ include "gateways.labels.standard" (dict "gatewayValues" $gateway "customLabels" $labels "context" $) | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- $annotations := merge $.Values.serviceAccount.annotations $.Values.commonAnnotations (and .serviceAccount .serviceAccount.annotations) }}
  {{- if $annotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
