{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled .Values.metrics.prometheusRule.groups }}
{{- if not (eq (include "common.capabilities.coreosMonitoring.apiVersion" .) "false") }}
apiVersion: {{ include "common.capabilities.coreosMonitoring.apiVersion" . }}
kind: PrometheusRule
metadata:
  name: {{ template "netbox.fullname" . }}
  namespace: {{ default (include "common.names.namespace" .) .Values.metrics.prometheusRule.namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.metrics.prometheusRule.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: netbox
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  groups: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.groups "context" .) | nindent 4 }}
{{- end }}
{{- end }}
