{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.envvarsConfigMap.enabled (not .Values.envvarsConfigMap.existingConfigMapName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "st-common.names.envvars" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  MTX_RTSPTRANSPORTS: tcp

  {{- if not (empty .Values.envvarsConfigMap.extraConfigs) }}
  {{- include "st-common.tplvalues.render" ( dict "value" .Values.envvarsConfigMap.extraConfigs "context" $ ) | nindent 2 }}
  {{- end }}

{{- end }}
