{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.gateway.enabled (eq .Values.gateway.implementation "istio") (not .Values.gateway.virtualService.existingVirtualService) }}
{{- if (include "st-common.capabilities.istioVirtualService.apiVersion" .) }}
{{- $clusterDomain := default .Values.clusterDomain .Values.gateway.clusterDomain -}}
apiVersion: {{ include "st-common.capabilities.istioVirtualService.apiVersion" . }}
kind: VirtualService
metadata:
  name: {{ include "st-common.names.fullname" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  gateways:
    - {{ include "st-common.gateway.fullname" . }}
  hosts:
    {{- if .Values.gateway.hostnames }}
    {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
    {{- else }}
    - "*"
    {{- end }}
  http:
    {{- if .Values.gateway.virtualService.http }}
    {{- include "st-common.tplvalues.render" (dict "value" .Values.gateway.virtualService.http "context" $) | nindent 4 }}
    {{- else }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ printf "%s.%s.svc.%s" (include "st-common.names.fullname" .) (include "st-common.names.namespace" .) $clusterDomain }}
            port:
              number: {{ .Values.service.ports.http }}
    {{- end }}
  {{- if .Values.tls.enabled }}
  tls:
    - match:
        - port: {{ default 443 .Values.service.ports.https | int }}
          sniHosts:
            {{- if .Values.gateway.hostnames }}
            {{- range .Values.gateway.hostnames }}
            - {{ . | quote }}
            {{- end }}
            {{- else }}
            - "*"
            {{- end }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.%s" (include "st-common.names.fullname" .) (include "st-common.names.namespace" .) $clusterDomain }}
            port:
              number: {{ .Values.service.ports.https }}
  {{- end }}
{{- end }}
{{- end }}
