## (c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.

apiVersion: v2
appVersion: 1.17.1
dependencies:
  - name: st-common
    repository: https://startechnica.github.io/apps
    version: 0.1.16
    alias: startechnica-common
description: PJP3 Lite mediamtx Helm Chart for Kubernetes
home: https://github.com/startechnica/apps/tree/main/charts/mediamtx
icon: https://raw.githubusercontent.com/bluenviron/mediamtx/master/.github/logo.png
keywords:
  - mediamtx
kubeVersion: ">=1.25.0"
maintainers:
  - name: Firmansyah Nainggolan
    email: firmansyah@nainggolan.id
    url: https://firmansyah.nainggolan.id
name: mediamtx
sources:
  - https://github.com/bluenviron/mediamtx
type: application
version: 0.1.0
