{{- if and .Values.gateway.enabled .Values.gateway.serviceEntry.enabled (not .Values.gateway.existingServiceEntry) (not .Values.gateway.gatewayApi.create) -}}
{{- $istioApiVersion := include "st-common.capabilities.istioServiceEntry.apiVersion" . -}}
{{- if and $istioApiVersion (ne $istioApiVersion "false") (ne $istioApiVersion "<no value>") -}}
apiVersion: {{ $istioApiVersion }}
kind: ServiceEntry
metadata:
  name: {{ include "netbox.fullname" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- range .Values.gateway.serviceEntry.hosts }}
    - {{ . | quote }}
    {{- end }}
  location: {{ default "MESH_EXTERNAL" .Values.gateway.serviceEntry.location }}
  resolution: {{ default "DNS" .Values.gateway.serviceEntry.resolution }}
  {{- if .Values.gateway.serviceEntry.ports }}
  ports:
    {{- include "st-common.tplvalues.render" (dict "value" .Values.gateway.serviceEntry.ports "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.gateway.serviceEntry.exportTo }}
  exportTo:
    {{- range .Values.gateway.serviceEntry.exportTo }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
