{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $implementation := default "gateway-api" .Values.gateway.implementation -}}
{{- if and .Values.gateway.enabled (eq $implementation "istio") (not .Values.gateway.virtualService.existingVirtualService) -}}
{{- $istioApiVersion := include "st-common.capabilities.istioVirtualService.apiVersion" . -}}
{{- if and $istioApiVersion (ne $istioApiVersion "false") -}}
{{- $clusterDomain := default (default "cluster.local" .Values.clusterDomain) .Values.gateway.clusterDomain -}}
{{- $hostnames := include "netbox.gateway.hostnames" . | trim -}}
apiVersion: {{ $istioApiVersion }}
kind: VirtualService
metadata:
  name: {{ include "st-common.names.fullname" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: netbox
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  {{- $annotations := include "st-common.tplvalues.merge" (dict "values" (list .Values.ingress.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  gateways:
    - {{ printf "%s/%s" (include "netbox.gateway.namespace" .) (include "netbox.gateway.fullname" .) }}
  hosts:
    {{- if $hostnames }}
    {{- $hostnames | nindent 4 }}
    {{- else }}
    - "*"
    {{- end }}
  http:
    - match:
        - uri:
            prefix: {{ default "/" .Values.ingress.path | quote }}
        {{- range .Values.ingress.extraPaths }}
        - uri:
            prefix: {{ .path | quote }}
        {{- end }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.%s" (include "st-common.names.fullname" $) (include "st-common.names.namespace" .) $clusterDomain }}
            port:
              number: {{ .Values.service.ports.http }}
  {{- if .Values.gateway.virtualService.tls }}
  tls:
    {{- include "st-common.tplvalues.render" (dict "value" .Values.gateway.virtualService.tls "context" $) | nindent 4 }}
  {{- else if or .Values.tls.enabled .Values.ingress.tls }}
  tls:
    - match:
        - port: 443
          sniHosts:
            {{- if $hostnames }}
            {{- $hostnames | nindent 12 }}
            {{- else }}
            - "*"
            {{- end }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.%s" (include "st-common.names.fullname" .) (include "st-common.names.namespace" .) $clusterDomain }}
  {{- end }}
  {{- if .Values.gateway.virtualService.tcp }}
  tcp:
    {{- include "st-common.tplvalues.render" (dict "value" .Values.gateway.virtualService.tcp "context" $) | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
