{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.gateway.enabled .Values.gateway.tls.enabled }}
{{- if .Values.gateway.tls.secrets }}
{{- range .Values.gateway.tls.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "st-common.gateway.namespace" $ | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
{{- if and .Values.gateway.tls.selfSigned (not .Values.tls.certManager.create) (not .Values.gateway.tls.existingSecret) (not .Values.gateway.tls.secrets) }}
{{- include "adminer.tls.ca.init" . }}
{{- $ca := index $ "_adminerTlsCa" }}
{{- $secretName := include "adminer.gateway.tlsSecretName" . }}
{{- $primaryHost := default .Values.ingress.hostname (first .Values.gateway.hostnames) }}
{{- $altNames := default (list $primaryHost) .Values.gateway.hostnames }}
{{- $cert := genSignedCert $primaryHost nil $altNames 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "st-common.gateway.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
{{- end }}
