{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if eq (include "netbox.tls.certManager.create" .) "true" -}}
apiVersion: {{ include "st-common.capabilities.certmanagerCertificate.apiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "st-common.names.fullname" . }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ printf "%s-tls" (include "st-common.names.fullname" .) }}
  issuerRef:
    kind: {{ include "netbox.tls.certManager.issuerKind" . }}
    name: {{ include "netbox.tls.certManager.issuerName" . }}
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    organizations:
      - {{ include "st-common.names.namespace" . | quote }}
    organizationalUnits:
      - {{ include "st-common.names.fullname" . }}
  dnsNames:
    - {{ .Values.ingress.hostname }}
    {{- range .Values.ingress.extraHosts }}
    - {{ .name | quote }}
    {{- end }}
---
{{- if and .Values.gateway.enabled (ne (include "netbox.gateway.namespace" .) (include "st-common.names.namespace" .)) }}
apiVersion: {{ include "st-common.capabilities.certmanagerCertificate.apiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "st-common.names.fullname" . }}
  namespace: {{ include "netbox.gateway.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "netbox.gateway.tlsSecretName" . }}
  issuerRef:
    kind: {{ include "netbox.tls.certManager.issuerKind" . }}
    name: {{ include "netbox.tls.certManager.issuerName" . }}
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    organizations:
      - {{ .Release.Name | quote }}
    organizationalUnits:
      - {{ include "st-common.names.fullname" . }}
  dnsNames:
    - {{ .Values.ingress.hostname }}
    {{- range .Values.ingress.extraHosts }}
    - {{ .name | quote }}
    {{- end }}
{{- end }}
{{- end -}}
