{{- if not .Values.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "netbox.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecretName) }}
  db-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s" (include "netbox.databaseSecretName" .)) "key" (printf "%s" (include "netbox.databaseSecretPasswordKey" .)) "length" 32 "providedValues" (list "externalDatabase.password") "context" $) }}
  {{- end }}
  {{- if not .Values.email.existingSecretName }}
  email_password: {{ .Values.email.password | b64enc | quote }}
  # email_password: {{ include "common.secrets.lookup" (dict "secret" (include "netbox.email.secretName" .) "key" (include "netbox.email.secretPasswordKey" .) "defaultValue" .Values.email.password "context" $) }}
  {{- end }}
  {{ if and (not .Values.redis.enabled) (not .Values.tasksRedis.existingSecretName) -}}
  redis-tasks-password: {{ .Values.tasksRedis.password | b64enc | quote }}
  {{ end -}}
  {{- if and (not .Values.redis.enabled) (not .Values.cachingRedis.existingSecretName) }}
  redis-cache-password: {{ .Values.cachingRedis.password | b64enc | quote }}
  {{- end }}
  # secret_key: {{ .Values.secretKey | default (randAscii 60) | b64enc }}
  secret_key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "netbox.secretName" .) "key" (include "netbox.secretSecretKeyKey" .) "length" 64 "providedValues" (list "secretKey") "context" $) }}
  {{- if not .Values.superuser.existingSecretName }}
  # superuser_password: {{ .Values.superuser.password | default (randAlphaNum 16) | b64enc }}
  # superuser_api_token: {{ .Values.superuser.apiToken | default uuidv4 | b64enc }}
  superuser_password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s" (include "netbox.superuser.secretName" .)) "key" (printf "%s" (include "netbox.superuser.secretPasswordKey" .)) "length" 16 "providedValues" (list "superuser.password") "context" $) }}
  superuser_api_token: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s" (include "netbox.superuser.secretName" .)) "key" (printf "%s" (include "netbox.superuser.secretApiTokenKey" .)) "length" 32 "providedValues" (list "superuser.apiToken") "context" $) }}
  {{- end }}
  {{- if (has "netbox.authentication.LDAPBackend" .Values.remoteAuth.backends) }}
  {{ include "netbox.superuser.secretPasswordKey" . }}: {{ .Values.remoteAuth.ldap.bindPassword | b64enc | quote }}
  {{- end }}
{{- end -}}
