{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.sites.dhcp.enabled (not .Values.sites.dhcp.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-sites-dhcp" (include "st-common.names.fullname" .) }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: freeradius
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  dhcp: |
    # -*- text -*-
    # DHCP virtual server

    server dhcp {

    listen {
        type = dhcp
        ipaddr = 0.0.0.0
        src_ipaddr = 127.0.0.1
        port = 6700
    #    interface = lo0
        broadcast = no

        performance {
            skip_duplicate_checks = no
        }
    }

    dhcp DHCP-Discover {

        update control {
            &DHCP-DHCP-Server-Identifier = 192.0.2.2
        }

        dhcp_common

        #dhcp_group_membership

        #dhcp_override_network

        #dhcp_network

        #mac2ip

        #update control {
        #    &Pool-Name := "local"
        #}
        #dhcp_sqlippool

        #if (notfound) {
        # ...
        #}

        #dhcp_subnet

        #dhcp_group_options

        #dhcp_hosts

        #dhcp_policy_sql

        #update reply {
        #       DHCP-Message-Type = DHCP-Offer
        #}
        #ok
    }

    dhcp DHCP-Request {

        update control {
            &DHCP-DHCP-Server-Identifier = 192.0.2.2
        }

        if (&request:DHCP-DHCP-Server-Identifier && \
            &request:DHCP-DHCP-Server-Identifier != &control:DHCP-DHCP-Server-Identifier) {
            do_not_respond
        }

        #update reply {
        #       &DHCP-Message-Type = DHCP-Ack
        #}

        dhcp_common

        #dhcp_group_membership

        #dhcp_override_network

        #dhcp_network

        #mac2ip

    #    update control {
    #        &Pool-Name := "local"
    #    }
    #    dhcp_sqlippool_request

        #if (notfound) {
        # ...
        #}

        #dhcp_subnet

        #dhcp_group_options

        #dhcp_hosts

        #dhcp_policy_sql

        #ok
    }

    dhcp DHCP-Decline {

        #dhcp_group_membership

        #dhcp_override_network

        #dhcp_network

        #dhcp_policy_sql

    #    update control {
    #        &Pool-Name := "local"
    #    }
    #    dhcp_sqlippool_decline

        update reply {
               &DHCP-Message-Type = DHCP-Do-Not-Respond
        }
        reject
    }

    dhcp DHCP-Inform {
        dhcp_common

        #dhcp_group_membership

        #dhcp_override_network

        #dhcp_network

        #dhcp_subnet

        #dhcp_group_options

        #dhcp_hosts

        #dhcp_policy_sql

        ok
    }

    # For Windows 7 boxes
    #dhcp DHCP-Inform {
    #    update reply {
    #        Packet-Dst-Port = 67
    #        DHCP-Message-Type = DHCP-ACK
    #        DHCP-DHCP-Server-Identifier = "%{Packet-Dst-IP-Address}"
    #        DHCP-Site-specific-28 = 0x0a00
    #    }
    #    ok
    #}

    dhcp DHCP-Release {

        #dhcp_group_membership

        #dhcp_override_network

        #dhcp_network

    #    update control {
    #        &Pool-Name := "local"
    #    }
    #    dhcp_sqlippool_release

        update reply {
               &DHCP-Message-Type = DHCP-Do-Not-Respond
        }
        reject
    }


    dhcp DHCP-Lease-Query {
        if (&DHCP-Client-Hardware-Address) {
            # look up MAC in database
        }
        elsif (&DHCP-Your-IP-Address) {
            # look up IP in database
        }
        elsif (&DHCP-Client-Identifier) {
            # look up identifier in database
        }
        else {
            update reply {
                &DHCP-Message-Type = DHCP-Lease-Unknown
            }

            ok
            return
        }

        if (notfound) {
            update reply {
                &DHCP-Message-Type = DHCP-Lease-Unknown
            }
            ok
            return
        }

        update reply {
            &DHCP-Message-Type = DHCP-Lease-Unassigned
        }

    }

    }

    # passwd mac2ip module — example, see mods-available/mac2ip
    #passwd mac2ip {
    #    filename = ${confdir}/mac2ip
    #    format = "*DHCP-Client-Hardware-Address:=DHCP-Your-IP-Address"
    #    delimiter = ","
    #}
{{- end }}
