{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.modules.pam.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-mods-pam" (include "st-common.names.fullname" .) }}
  namespace: {{ include "st-common.names.namespace" . | quote }}
  labels: {{- include "st-common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: freeradius
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  pam: |
    {{- include "freeradius.tplvalues.renderConfig" (dict "value" (dict "pam" (omit .Values.modules.pam "enabled")) "context" $) | nindent 4 }}
{{- end }}
