{{- if and .Values.ingress.tls .Values.ingress.certManager.create (not .Values.ingress.selfSigned) }}
{{- if (include "common.capabilities.certManager.apiVersion" .) }}
apiVersion: {{ include "common.capabilities.certManager.apiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
  issuerRef:
    group: {{ .Values.ingress.certManager.issuerRef.group }}
    kind: {{ .Values.ingress.certManager.issuerRef.kind }}
    name: {{ .Values.ingress.certManager.issuerRef.name }}
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    organizations:
      - {{ .Release.Name | quote }}
    organizationalUnits:
      - {{ include "common.names.fullname" . }}
  dnsNames:
    - {{ .Values.ingress.hostname | quote }}
    {{- range .Values.ingress.extraHosts }}
    - {{ .name | quote }}
    {{- end }}
---
{{- if .Values.gateway.enabled }}
apiVersion: {{ include "common.capabilities.certManager.apiVersion" . }}
kind: Certificate
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Values.gateway.namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
  issuerRef:
    group: {{ .Values.ingress.certManager.issuerRef.group }}
    kind: {{ .Values.ingress.certManager.issuerRef.kind }}
    name: {{ .Values.ingress.certManager.issuerRef.name }}
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    organizations:
      - {{ .Release.Name | quote }}
    organizationalUnits:
      - {{ include "common.names.fullname" . }}
  dnsNames:
    - {{ .Values.ingress.hostname | quote }}
    {{- range .Values.ingress.extraHosts }}
    - {{ .name | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}