{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
{{- if not (eq (include "st-common.capabilities.coreosMonitoringPrometheusRule.apiVersion" .) "false") -}}
apiVersion: {{ include "st-common.capabilities.coreosMonitoringPrometheusRule.apiVersion" . }}
kind: PrometheusRule
metadata:
  name: {{ template "st-common.names.fullname" . }}
  namespace: {{ default (include "st-common.names.namespace" .) .Values.metrics.prometheusRule.namespace | quote }}
  labels: {{- include "st-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- if .Values.metrics.prometheusRule.additionalLabels }}
    {{- include "st-common.tplvalues.render" (dict "value" .Values.metrics.prometheusRule.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "st-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "st-common.names.fullname" . }}
      rules: {{- include "st-common.tplvalues.render" ( dict "value" .Values.metrics.prometheusRule.rules "context" $ ) | nindent 8 }}
{{- end }}
{{- end -}}
