{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
SQL backend helpers — anything namespaced under `freeradius.sql.*`, plus the
bundled-subchart `fullname` helpers that the SQL connection resolution
internally relies on (`freeradius.mariadb.fullname`,
`freeradius.postgresql.fullname`).

Two layers of resolution live here:

  1. SQL backend TLS material — `freeradius.sql.tls.{certPath,certKeyPath,
     caCertPath,secretName,createSecret}`. Independent of the in-pod RADSEC
     TLS namespace (top-level `tls.*`, helpers in `_helpers.tpl`) and of the
     REST module TLS namespace (`modules.rest.tls.*`, also in `_helpers.tpl`).

  2. SQL connection — `freeradius.sql.{host,port,name,user,secretName,
     secretKey}`. Three-way branch: bundled MariaDB subchart →
     bundled PostgreSQL subchart → user-supplied `externalDatabase.*`,
     first match wins. The coherence rules (one subchart at a time,
     dialect must match the chosen subchart, etc.) are enforced by
     `freeradius.validate.sql.backend` in `templates/helpers/_validate.tpl`.

The schema-bootstrap helpers (`freeradius.bootstrap.database.*`) live in
the chart-wide `_helpers.tpl` since they straddle the SQL/init-container
boundary rather than belonging strictly to either.
*/}}

{{/*
Bundled-subchart fullnames. Resolved via `st-common.names.dependency.fullname`
so they honour `fullnameOverride` and the subchart's own naming knobs.
*/}}
{{- define "freeradius.mariadb.fullname" -}}
  {{- include "st-common.names.dependency.fullname" (dict "chartName" "mariadb" "chartValues" .Values.mariadb "context" $) -}}
{{- end -}}

{{- define "freeradius.postgresql.fullname" -}}
  {{- include "st-common.names.dependency.fullname" (dict "chartName" "postgresql" "chartValues" .Values.postgresql "context" $) -}}
{{- end -}}

{{/*
SQL backend TLS — separate namespace from the in-pod RADSEC TLS in
`_helpers.tpl`. Material paths assume the SQL TLS Secret is mounted at
`/opt/startechnica/freeradius/certs` (see Deployment.yaml `freeradius-sql-tls`
volumeMount).
*/}}
{{- define "freeradius.sql.tls.certPath" -}}
{{- if .Values.modules.sql.tls.enabled -}}
  {{- if .Values.modules.sql.tls.autoGenerated -}}
    {{- printf "/opt/startechnica/freeradius/certs/sql-tls.crt" -}}
  {{- else if .Values.modules.sql.tls.certFilename -}}
    {{- printf "/opt/startechnica/freeradius/certs/%s" .Values.modules.sql.tls.certFilename -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.sql.tls.certKeyPath" -}}
{{- if .Values.modules.sql.tls.enabled -}}
  {{- if .Values.modules.sql.tls.autoGenerated -}}
    {{- printf "/opt/startechnica/freeradius/certs/sql-tls.key" -}}
  {{- else if .Values.modules.sql.tls.certKeyFilename -}}
    {{- printf "/opt/startechnica/freeradius/certs/%s" .Values.modules.sql.tls.certKeyFilename -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.sql.tls.caCertPath" -}}
{{- if .Values.modules.sql.tls.enabled -}}
  {{- if .Values.modules.sql.tls.autoGenerated -}}
    {{- printf "/opt/startechnica/freeradius/certs/sql-ca.crt" -}}
  {{- else if .Values.modules.sql.tls.certCAFilename -}}
    {{- printf "/opt/startechnica/freeradius/certs/%s" .Values.modules.sql.tls.certCAFilename -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.sql.tls.secretName" -}}
{{- if .Values.modules.sql.tls.certificatesSecret -}}
{{- .Values.modules.sql.tls.certificatesSecret -}}
{{- else if .Values.modules.sql.tls.existingTlsSecret -}}
{{- .Values.modules.sql.tls.existingTlsSecret -}}
{{- else -}}
{{- printf "%s-sql-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.sql.tls.createSecret" -}}
{{- if and .Values.modules.sql.tls.enabled .Values.modules.sql.tls.autoGenerated (not .Values.modules.sql.tls.certificatesSecret) (not .Values.modules.sql.tls.existingTlsSecret) -}}
true
{{- end -}}
{{- end -}}

{{/*
SQL backend connection helpers — single source of truth for both the env-vars
ConfigMap (`FREERADIUS_MODS_SQL_*`) and the `db-bootstrap` init container.

Resolution order (first match wins):
  1. `mariadb.enabled`     → bundled MariaDB subchart (mysql wire protocol).
  2. `postgresql.enabled`  → bundled PostgreSQL subchart (postgresql wire protocol).
  3. `externalDatabase.*`  → user-supplied external database (any dialect).

The chart's `freeradius.validate.sql.backend` aggregator rejects misconfigurations
(two subcharts at once, dialect/subchart mismatch, sqlite + subchart, etc.)
before any resource is applied.
*/}}
{{- define "freeradius.sql.host" -}}
{{- if .Values.mariadb.enabled -}}
  {{- if eq .Values.mariadb.architecture "replication" -}}
    {{- printf "%s-primary" (include "freeradius.mariadb.fullname" .) -}}
  {{- else -}}
    {{- include "freeradius.mariadb.fullname" . -}}
  {{- end -}}
{{- else if .Values.postgresql.enabled -}}
  {{- if eq .Values.postgresql.architecture "replication" -}}
    {{- printf "%s-primary" (include "freeradius.postgresql.fullname" .) -}}
  {{- else -}}
    {{- include "freeradius.postgresql.fullname" . -}}
  {{- end -}}
{{- else -}}
  {{- .Values.externalDatabase.host -}}
{{- end -}}
{{- end -}}

{{/*
SQL backend port. Bundled subcharts use their well-known defaults; for the
external case, `externalDatabase.port` wins when set, otherwise the chart
defaults from `modules.sql.dialect` (3306 mysql, 5432 postgresql).
*/}}
{{- define "freeradius.sql.port" -}}
{{- if .Values.mariadb.enabled -}}
  {{- print "3306" | quote -}}
{{- else if .Values.postgresql.enabled -}}
  {{- print "5432" | quote -}}
{{- else if .Values.externalDatabase.port -}}
  {{- .Values.externalDatabase.port | toString | quote -}}
{{- else if eq .Values.modules.sql.dialect "postgresql" -}}
  {{- print "5432" | quote -}}
{{- else -}}
  {{- print "3306" | quote -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.sql.name" -}}
{{- if .Values.mariadb.enabled -}}
  {{- if and .Values.global.mariadb .Values.global.mariadb.auth -}}
    {{- coalesce .Values.global.mariadb.auth.database .Values.mariadb.auth.database -}}
  {{- else -}}
    {{- .Values.mariadb.auth.database -}}
  {{- end -}}
{{- else if .Values.postgresql.enabled -}}
  {{- if and .Values.global.postgresql .Values.global.postgresql.auth -}}
    {{- coalesce .Values.global.postgresql.auth.database .Values.postgresql.auth.database -}}
  {{- else -}}
    {{- .Values.postgresql.auth.database -}}
  {{- end -}}
{{- else -}}
  {{- .Values.externalDatabase.database -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.sql.user" -}}
{{- if .Values.mariadb.enabled -}}
  {{- if and .Values.global.mariadb .Values.global.mariadb.auth -}}
    {{- coalesce .Values.global.mariadb.auth.username .Values.mariadb.auth.username -}}
  {{- else -}}
    {{- .Values.mariadb.auth.username -}}
  {{- end -}}
{{- else if .Values.postgresql.enabled -}}
  {{- if and .Values.global.postgresql .Values.global.postgresql.auth -}}
    {{- coalesce .Values.global.postgresql.auth.username .Values.postgresql.auth.username -}}
  {{- else -}}
    {{- .Values.postgresql.auth.username -}}
  {{- end -}}
{{- else -}}
  {{- .Values.externalDatabase.user -}}
{{- end -}}
{{- end -}}

{{/*
Name of the Secret holding the SQL backend password. For bundled subcharts the
chart points at the subchart's own auth secret (so credentials stay in lockstep
with what the subchart provisions). For external databases, the user's existing
Secret wins, otherwise the chart-managed credentials Secret.
*/}}
{{- define "freeradius.sql.secretName" -}}
{{- if .Values.mariadb.enabled -}}
  {{- if and .Values.global.mariadb .Values.global.mariadb.auth .Values.global.mariadb.auth.existingSecret -}}
    {{- tpl .Values.global.mariadb.auth.existingSecret $ -}}
  {{- else -}}
    {{- default (include "freeradius.mariadb.fullname" .) (tpl .Values.mariadb.auth.existingSecret $) -}}
  {{- end -}}
{{- else if .Values.postgresql.enabled -}}
  {{- if and .Values.global.postgresql .Values.global.postgresql.auth .Values.global.postgresql.auth.existingSecret -}}
    {{- tpl .Values.global.postgresql.auth.existingSecret $ -}}
  {{- else -}}
    {{- default (include "freeradius.postgresql.fullname" .) (tpl .Values.postgresql.auth.existingSecret $) -}}
  {{- end -}}
{{- else -}}
  {{- default (include "st-common.secrets.name" (dict "existingSecret" .Values.auth.existingSecret "context" $)) (tpl .Values.externalDatabase.existingSecret $) -}}
{{- end -}}
{{- end -}}

{{/*
Key inside `freeradius.sql.secretName` that holds the SQL backend password.
The Bitnami subcharts use different key names: mariadb stores it under
`mariadb-password`, postgresql under `password`.
*/}}
{{- define "freeradius.sql.secretKey" -}}
{{- if .Values.mariadb.enabled -}}
  {{- print "mariadb-password" -}}
{{- else if .Values.postgresql.enabled -}}
  {{- print "password" -}}
{{- else if and .Values.externalDatabase.existingSecret .Values.externalDatabase.existingSecretPasswordKey -}}
  {{- printf "%s" .Values.externalDatabase.existingSecretPasswordKey -}}
{{- else -}}
  {{- print "database-password" -}}
{{- end -}}
{{- end -}}
