{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
RADSEC in-pod TLS secret name. Resolution order:
  1. tls.certificatesSecret      — BYO Secret (chart-managed leaf).
  2. tls.existingSecretName      — deprecated alias (kept for backwards compatibility).
  3. <fullname>-tls              — chart-managed default (auto-generated, cert-manager, etc.).
*/}}
{{- define "freeradius.tls.secretName" -}}
{{- if .Values.tls.certificatesSecret -}}
{{- .Values.tls.certificatesSecret -}}
{{- else if .Values.tls.existingSecretName -}}
{{- .Values.tls.existingSecretName -}}
{{- else -}}
{{- printf "%s-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Whether the chart should render `templates/secret/tls.yaml` with a self-signed
RADSEC leaf. False when the user is bringing their own Secret or cert-manager
owns issuance.
*/}}
{{- define "freeradius.tls.createSecret" -}}
{{- if and .Values.tls.enabled .Values.tls.autoGenerated (not .Values.tls.certificatesSecret) (not .Values.tls.existingSecretName) (not .Values.tls.certManager.create) -}}
true
{{- end -}}
{{- end -}}

{{/*
RADSEC in-pod TLS material paths (used by the env-vars ConfigMap to point
FreeRADIUS at the certificate files mounted from the Secret).
*/}}
{{- define "freeradius.tls.certPath" -}}
{{- if .Values.tls.certFilename -}}
  {{- printf "%s/%s" .Values.tls.certificatesMountPath .Values.tls.certFilename -}}
{{- else -}}
  {{- printf "%s/tls.crt" .Values.tls.certificatesMountPath -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.tls.certKeyPath" -}}
{{- if .Values.tls.certKeyFilename -}}
  {{- printf "%s/%s" .Values.tls.certificatesMountPath .Values.tls.certKeyFilename -}}
{{- else -}}
  {{- printf "%s/tls.key" .Values.tls.certificatesMountPath -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.tls.caCertPath" -}}
{{- if .Values.tls.certCAFilename -}}
  {{- printf "%s/%s" .Values.tls.certificatesMountPath .Values.tls.certCAFilename -}}
{{- else -}}
  {{- printf "%s/ca.crt" .Values.tls.certificatesMountPath -}}
{{- end -}}
{{- end -}}

{{/*
REST module TLS — third TLS namespace (after RADSEC and SQL).
Material paths assume the REST TLS Secret is mounted at
`/opt/startechnica/freeradius/certs-rest` (see Deployment.yaml
`freeradius-rest-tls` volumeMount). Each *Path helper returns the empty string
when its source material isn't configured, so rlm_rest's `tls{}` block falls
back to the system CA bundle / no client cert.
*/}}
{{- define "freeradius.rest.tls.certPath" -}}
{{- if .Values.modules.rest.tls.enabled -}}
  {{- if .Values.modules.rest.tls.certFilename -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/%s" .Values.modules.rest.tls.certFilename -}}
  {{- else if or .Values.modules.rest.tls.autoGenerated .Values.modules.rest.tls.certificatesSecret -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/tls.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.certKeyPath" -}}
{{- if .Values.modules.rest.tls.enabled -}}
  {{- if .Values.modules.rest.tls.certKeyFilename -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/%s" .Values.modules.rest.tls.certKeyFilename -}}
  {{- else if or .Values.modules.rest.tls.autoGenerated .Values.modules.rest.tls.certificatesSecret -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/tls.key" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.caCertPath" -}}
{{- if .Values.modules.rest.tls.enabled -}}
  {{- if .Values.modules.rest.tls.certCAFilename -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/%s" .Values.modules.rest.tls.certCAFilename -}}
  {{- else if or .Values.modules.rest.tls.autoGenerated .Values.modules.rest.tls.certificatesSecret -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/ca.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.secretName" -}}
{{- if .Values.modules.rest.tls.certificatesSecret -}}
{{- .Values.modules.rest.tls.certificatesSecret -}}
{{- else -}}
{{- printf "%s-rest-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.createSecret" -}}
{{- if and .Values.modules.rest.enabled .Values.modules.rest.tls.enabled .Values.modules.rest.tls.autoGenerated (not .Values.modules.rest.tls.certificatesSecret) -}}
true
{{- end -}}
{{- end -}}

{{/*
EAP module tls-config — fourth TLS namespace (after RADSEC, SQL, REST). This
is the shared `tls-config tls-common` server certificate (NOT the EAP-TLS
method, which is `modules.eap.tls`). Material is MANDATORY whenever the
module is enabled (TLS-based EAP methods can't run without a server cert), so
the path helpers gate on `modules.eap.enabled` rather than a per-method toggle.
Secret is mounted at `/opt/startechnica/freeradius/certs-eap` (see
Deployment.yaml `freeradius-eap-tls` volumeMount).
*/}}
{{- define "freeradius.eap.tlsConfig.certPath" -}}
{{- if .Values.modules.eap.enabled -}}
  {{- if .Values.modules.eap.tlsConfig.cert_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/%s" .Values.modules.eap.tlsConfig.cert_filename -}}
  {{- else -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/tls.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.certKeyPath" -}}
{{- if .Values.modules.eap.enabled -}}
  {{- if .Values.modules.eap.tlsConfig.cert_key_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/%s" .Values.modules.eap.tlsConfig.cert_key_filename -}}
  {{- else -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/tls.key" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.caCertPath" -}}
{{- if .Values.modules.eap.enabled -}}
  {{- if .Values.modules.eap.tlsConfig.cert_ca_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/%s" .Values.modules.eap.tlsConfig.cert_ca_filename -}}
  {{- else -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/ca.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.secretName" -}}
{{- if .Values.modules.eap.tlsConfig.certificates_secret -}}
{{- .Values.modules.eap.tlsConfig.certificates_secret -}}
{{- else -}}
{{- printf "%s-eap-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.createSecret" -}}
{{- if and .Values.modules.eap.enabled .Values.modules.eap.tlsConfig.autoGenerated (not .Values.modules.eap.tlsConfig.certificates_secret) -}}
true
{{- end -}}
{{- end -}}

{{/*
Name of the Kubernetes Secret holding the TLS material referenced by the
Gateway TLS listener — `credentialName` on the istio path,
`certificateRefs[].name` on the gateway-api path, and the resource name
produced by `templates/secret/gateway-tls.yaml`. Single source of truth so
the listener and the secret can never drift apart.

Resolution order (first match wins):
  1. `gateway.tls.existingSecret`       — BYO Secret managed outside the chart.
  2. `gateway.tls.secrets[0].name`      — first user-supplied PEM Secret rendered by `templates/secret/gateway-tls.yaml`.
                                          For multi-secret SNI setups, override via `gateway.listeners`.
  3. `<gateway-hostname>-tls`           — chart-managed default that matches the secret name produced by the
                                          self-signed branch in `templates/secret/gateway-tls.yaml` and the
                                          `Certificate.spec.secretName` in `templates/Certificate.yaml`.
                                          Falls back to `<fullname>-tls` when no hostnames are configured.
*/}}
{{- define "freeradius.gateway.tlsSecretName" -}}
{{- if .Values.gateway.tls.existingSecret -}}
{{- .Values.gateway.tls.existingSecret -}}
{{- else if .Values.gateway.tls.secrets -}}
{{- (first .Values.gateway.tls.secrets).name -}}
{{- else if .Values.gateway.hostnames -}}
{{- printf "%s-tls" (first .Values.gateway.hostnames) -}}
{{- else -}}
{{- printf "%s-gateway-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Name of the chart-internal CA Secret (`<fullname>-tls-ca`) holding the
self-signed Certificate Authority shared by the in-pod RADSEC leaf and the
gateway-namespace leaf TLS Secrets.
*/}}
{{- define "freeradius.tls.ca.secretName" -}}
{{- printf "%s-tls-ca" (include "st-common.names.fullname" .) -}}
{{- end -}}

{{/*
Populates `$._freeradiusTlsCa` (root-context cache) with the chart's
self-signed TLS Certificate Authority — a sprig `certificate` struct
compatible with `genSignedCert`.

Recovery chain on first invocation per render:
  1. lookup the persistent CA Secret rendered by `templates/secret/tls-ca.yaml`
     in the release namespace; recover Cert+Key if present.
  2. otherwise fall back to `genCA` (first install path).
*/}}
{{- define "freeradius.tls.ca.init" -}}
{{- if not (hasKey $ "_freeradiusTlsCa") -}}
  {{- $existing := lookup "v1" "Secret" (include "st-common.names.namespace" .) (include "freeradius.tls.ca.secretName" .) -}}
  {{- $ca := "" -}}
  {{- if and $existing $existing.data (hasKey $existing.data "ca.crt") (hasKey $existing.data "ca.key") -}}
    {{- $ca = buildCustomCert (index $existing.data "ca.crt") (index $existing.data "ca.key") -}}
  {{- else -}}
    {{- $ca = genCA "freeradius-ca" 365 -}}
  {{- end -}}
  {{- $_ := set $ "_freeradiusTlsCa" $ca -}}
{{- end -}}
{{- end -}}
