{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
RADSEC in-pod TLS secret name. Resolution order:
  1. tls.certificatesSecret      — BYO Secret (chart-managed leaf).
  2. tls.existingSecretName      — deprecated alias (kept for backwards compatibility).
  3. <fullname>-tls              — chart-managed default (auto-generated, cert-manager, etc.).
*/}}
{{- define "freeradius.tls.secretName" -}}
{{- if .Values.tls.certificatesSecret -}}
{{- .Values.tls.certificatesSecret -}}
{{- else if .Values.tls.existingSecretName -}}
{{- .Values.tls.existingSecretName -}}
{{- else -}}
{{- printf "%s-radsec-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Whether the chart should render `templates/secrets/tls.yaml` with a self-signed
RADSEC leaf. False when the user is bringing their own Secret or cert-manager
owns issuance.
*/}}
{{- define "freeradius.tls.createSecret" -}}
{{- if and .Values.tls.enabled .Values.tls.autoGenerated (not .Values.tls.certificatesSecret) (not .Values.tls.existingSecretName) (not (include "freeradius.tls.useCertManager" .)) -}}
true
{{- end -}}
{{- end -}}

{{/*
RADSEC in-pod TLS material paths (used by the env-vars ConfigMap to point
FreeRADIUS at the certificate files mounted from the Secret).
*/}}
{{- define "freeradius.tls.certPath" -}}
{{- if .Values.tls.certFilename -}}
  {{- printf "%s/%s" .Values.tls.certificatesMountPath .Values.tls.certFilename -}}
{{- else -}}
  {{- printf "%s/tls.crt" .Values.tls.certificatesMountPath -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.tls.certKeyPath" -}}
{{- if .Values.tls.certKeyFilename -}}
  {{- printf "%s/%s" .Values.tls.certificatesMountPath .Values.tls.certKeyFilename -}}
{{- else -}}
  {{- printf "%s/tls.key" .Values.tls.certificatesMountPath -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.tls.caCertPath" -}}
{{- if .Values.tls.certCAFilename -}}
  {{- printf "%s/%s" .Values.tls.certificatesMountPath .Values.tls.certCAFilename -}}
{{- else -}}
  {{- printf "%s/ca.crt" .Values.tls.certificatesMountPath -}}
{{- end -}}
{{- end -}}

{{/*
REST module TLS — third TLS namespace (after RADSEC and SQL).
Material paths assume the REST TLS Secret is mounted at
`/opt/startechnica/freeradius/certs-rest` (see Deployment.yaml
`freeradius-rest-tls` volumeMount). Each *Path helper returns the empty string
when its source material isn't configured, so rlm_rest's `tls{}` block falls
back to the system CA bundle / no client cert.
*/}}
{{- define "freeradius.rest.tls.certPath" -}}
{{- if .Values.modules.rest.tls.enabled -}}
  {{- if .Values.modules.rest.tls.cert_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/%s" .Values.modules.rest.tls.cert_filename -}}
  {{- else if or .Values.modules.rest.tls.auto_generated .Values.modules.rest.tls.certificates_secret -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/tls.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.certKeyPath" -}}
{{- if .Values.modules.rest.tls.enabled -}}
  {{- if .Values.modules.rest.tls.cert_key_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/%s" .Values.modules.rest.tls.cert_key_filename -}}
  {{- else if or .Values.modules.rest.tls.auto_generated .Values.modules.rest.tls.certificates_secret -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/tls.key" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.caCertPath" -}}
{{- if .Values.modules.rest.tls.enabled -}}
  {{- if .Values.modules.rest.tls.cert_ca_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/%s" .Values.modules.rest.tls.cert_ca_filename -}}
  {{- else if or .Values.modules.rest.tls.auto_generated .Values.modules.rest.tls.certificates_secret -}}
    {{- printf "/opt/startechnica/freeradius/certs-rest/ca.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.secretName" -}}
{{- if .Values.modules.rest.tls.certificates_secret -}}
{{- .Values.modules.rest.tls.certificates_secret -}}
{{- else -}}
{{- printf "%s-rest-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.rest.tls.createSecret" -}}
{{- if and .Values.modules.rest.enabled .Values.modules.rest.tls.enabled .Values.modules.rest.tls.auto_generated (not .Values.modules.rest.tls.certificates_secret) -}}
true
{{- end -}}
{{- end -}}

{{/*
EAP module tls-config — fourth TLS namespace (after RADSEC, SQL, REST). This
is the shared `tls-config tls-common` server certificate (NOT the EAP-TLS
method, which is `modules.eap.tls`). Material is MANDATORY whenever the
module is enabled (TLS-based EAP methods can't run without a server cert), so
the path helpers gate on `modules.eap.enabled` rather than a per-method toggle.
Secret is mounted at `/opt/startechnica/freeradius/certs-eap` (see
Deployment.yaml `freeradius-eap-tls` volumeMount).
*/}}
{{- define "freeradius.eap.tlsConfig.certPath" -}}
{{- if .Values.modules.eap.enabled -}}
  {{- if .Values.modules.eap.tlsConfig.cert_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/%s" .Values.modules.eap.tlsConfig.cert_filename -}}
  {{- else -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/tls.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.certKeyPath" -}}
{{- if .Values.modules.eap.enabled -}}
  {{- if .Values.modules.eap.tlsConfig.cert_key_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/%s" .Values.modules.eap.tlsConfig.cert_key_filename -}}
  {{- else -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/tls.key" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.caCertPath" -}}
{{- if .Values.modules.eap.enabled -}}
  {{- if .Values.modules.eap.tlsConfig.cert_ca_filename -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/%s" .Values.modules.eap.tlsConfig.cert_ca_filename -}}
  {{- else -}}
    {{- printf "/opt/startechnica/freeradius/certs-eap/ca.crt" -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.secretName" -}}
{{- if .Values.modules.eap.tlsConfig.certificates_secret -}}
{{- .Values.modules.eap.tlsConfig.certificates_secret -}}
{{- else -}}
{{- printf "%s-eap-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{- define "freeradius.eap.tlsConfig.createSecret" -}}
{{- if and .Values.modules.eap.enabled .Values.modules.eap.tlsConfig.autoGenerated (not .Values.modules.eap.tlsConfig.certificates_secret) (not (include "freeradius.tls.useCertManager" .)) -}}
true
{{- end -}}
{{- end -}}

{{/*
Whether the chart should render a cert-manager `Certificate` for the EAP
`tls-config tls-common` server cert. True when cert-manager is in charge AND
the EAP module is enabled AND the user hasn't supplied their own Secret.
`autoGenerated: false` still disables it — the operator is opting out of chart
issuance entirely and must mount their own Secret via `certificates_secret`.
*/}}
{{- define "freeradius.eap.tlsConfig.createCertificate" -}}
{{- if and (include "freeradius.tls.useCertManager" .) .Values.modules.eap.enabled .Values.modules.eap.tlsConfig.autoGenerated (not .Values.modules.eap.tlsConfig.certificates_secret) -}}
true
{{- end -}}
{{- end -}}

{{/*
Name of the Kubernetes Secret holding the TLS material referenced by the
Gateway TLS listener — `credentialName` on the istio path,
`certificateRefs[].name` on the gateway-api path, and the resource name
produced by `templates/secrets/gateway-tls.yaml`. Single source of truth so
the listener and the secret can never drift apart.

Resolution order (first match wins):
  1. `gateway.tls.existingSecret`       — BYO Secret managed outside the chart.
  2. `gateway.tls.secrets[0].name`      — first user-supplied PEM Secret rendered by `templates/secrets/gateway-tls.yaml`.
                                          For multi-secret SNI setups, override via `gateway.listeners`.
  3. `<gateway-hostname>-tls`           — chart-managed default that matches the secret name produced by the
                                          self-signed branch in `templates/secrets/gateway-tls.yaml` and the
                                          `Certificate.spec.secretName` in `templates/Certificate.yaml`.
                                          Falls back to `<fullname>-tls` when no hostnames are configured.
*/}}
{{- define "freeradius.gateway.tlsSecretName" -}}
{{- if .Values.gateway.tls.existingSecret -}}
{{- .Values.gateway.tls.existingSecret -}}
{{- else if .Values.gateway.tls.secrets -}}
{{- (first .Values.gateway.tls.secrets).name -}}
{{- else if .Values.gateway.hostnames -}}
{{- printf "%s-tls" (first .Values.gateway.hostnames) -}}
{{- else -}}
{{- printf "%s-gateway-tls" (include "st-common.names.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Name of the chart-internal CA Secret (`<fullname>-tls-ca`) holding the
self-signed Certificate Authority shared by the in-pod RADSEC leaf and the
gateway-namespace leaf TLS Secrets.
*/}}
{{- define "freeradius.tls.ca.secretName" -}}
{{- printf "%s-tls-ca" (include "st-common.names.fullname" .) -}}
{{- end -}}

{{/*
Whether the chart should issue its TLS material through cert-manager rather than
the in-template genCA path. True when cert-manager issuance is requested
(`tls.certManager.create`, default true) AND the cluster actually exposes the
cert-manager Certificate API. When the API is absent the chart falls back to the
self-signed genCA path (`templates/secrets/tls.yaml` + `tls-ca.yaml`). Set
`tls.certManager.create: false` to force the genCA path even where cert-manager
is installed.

NOTE: `st-common.capabilities.certmanagerCertificate.apiVersion` returns the
string "false" (not an empty string) when the API is missing, so it must be
compared explicitly — a bare truthiness test treats "false" as true.
*/}}
{{- define "freeradius.tls.useCertManager" -}}
{{- if and .Values.tls.certManager.create (ne (include "st-common.capabilities.certmanagerCertificate.apiVersion" .) "false") -}}
true
{{- end -}}
{{- end -}}

{{/*
Cert-manager CA bootstrap. Active when the chart issues via cert-manager
(`freeradius.tls.useCertManager`) but no external issuer is supplied
(`tls.certManager.issuerRef.name` empty). In that case the chart renders its own
self-signed `Issuer` -> CA `Certificate` -> CA `Issuer` chain
(`templates/Issuer.yaml`) and the leaf Certificates reference the CA Issuer.
When `issuerRef.name` is set the leaves use that issuer instead.
*/}}
{{- define "freeradius.tls.certManager.bootstrapCA" -}}
{{- if and (include "freeradius.tls.useCertManager" .) (not .Values.tls.certManager.issuerRef.name) -}}
true
{{- end -}}
{{- end -}}

{{- define "freeradius.tls.certManager.selfSignedIssuerName" -}}
{{- printf "%s-selfsigned" (include "st-common.names.fullname" .) -}}
{{- end -}}

{{- define "freeradius.tls.certManager.caIssuerName" -}}
{{- printf "%s-ca" (include "st-common.names.fullname" .) -}}
{{- end -}}

{{- define "freeradius.tls.certManager.caSecretName" -}}
{{- default (printf "%s-ca" (include "st-common.names.fullname" .)) .Values.tls.certManager.ca.secretName -}}
{{- end -}}

{{/*
Effective `issuerRef` body for the leaf Certificates. Emits the chart-managed
CA Issuer when the bootstrap is active, otherwise the user-supplied issuer.
*/}}
{{- define "freeradius.tls.certManager.issuerRef" -}}
{{- if include "freeradius.tls.certManager.bootstrapCA" . -}}
group: cert-manager.io
kind: Issuer
name: {{ include "freeradius.tls.certManager.caIssuerName" . }}
{{- else -}}
group: {{ .Values.tls.certManager.issuerRef.group }}
kind: {{ .Values.tls.certManager.issuerRef.kind }}
name: {{ .Values.tls.certManager.issuerRef.name }}
{{- end -}}
{{- end -}}

{{/*
Populates `$._freeradiusTlsCa` (root-context cache) with the chart's
self-signed TLS Certificate Authority — a sprig `certificate` struct
compatible with `genSignedCert`.

Recovery chain on first invocation per render:
  1. lookup the persistent CA Secret rendered by `templates/secrets/tls-ca.yaml`
     in the release namespace; recover Cert+Key if present.
  2. otherwise fall back to `genCA` (first install path).
*/}}
{{- define "freeradius.tls.ca.init" -}}
{{- if not (hasKey $ "_freeradiusTlsCa") -}}
  {{- $existing := lookup "v1" "Secret" (include "st-common.names.namespace" .) (include "freeradius.tls.ca.secretName" .) -}}
  {{- $ca := "" -}}
  {{- if and $existing $existing.data (hasKey $existing.data "ca.crt") (hasKey $existing.data "ca.key") -}}
    {{- $ca = buildCustomCert (index $existing.data "ca.crt") (index $existing.data "ca.key") -}}
  {{- else -}}
    {{- $ca = genCA "freeradius-ca" 365 -}}
  {{- end -}}
  {{- $_ := set $ "_freeradiusTlsCa" $ca -}}
{{- end -}}
{{- end -}}
