{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
Hard-validation aggregator. Each `freeradius.validate.<area>` helper below
returns a non-empty string when its precondition is violated, otherwise the
empty string. This template gathers all of them, drops the empty entries,
and calls `fail` when anything remains so `helm install` / `helm upgrade` /
`helm template` reject the misconfigured release before any resource is
applied.

Included from `templates/NOTES.txt` (Helm renders NOTES.txt as part of the
install path, so a `fail` here aborts the operation).
*/}}
{{- define "freeradius.validate" -}}
{{- $messages := list -}}
{{- $messages = append $messages (include "freeradius.validate.tls" .) -}}
{{- $messages = append $messages (include "freeradius.validate.metrics" .) -}}
{{- $messages = append $messages (include "freeradius.validate.sql.backend" .) -}}
{{- $messages = append $messages (include "freeradius.validate.rest" .) -}}
{{- $messages = append $messages (include "freeradius.validate.eap" .) -}}
{{- $messages = append $messages (include "freeradius.validate.cache" .) -}}
{{- $messages = append $messages (include "freeradius.validate.tlsCache" .) -}}
{{- $messages = append $messages (include "freeradius.validate.cacheInstances" .) -}}
{{- $messages = append $messages (include "freeradius.validate.keycloakInstances" .) -}}
{{- $messages = append $messages (include "freeradius.validate.keycloakClientBindings" .) -}}
{{- $messages := without $messages "" -}}
{{- $message := join "\n" $messages -}}
{{- if $message -}}
{{- printf "\nVALUES VALIDATION:\n%s" $message | fail -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: RADSEC enabled but no cert source configured.
*/}}
{{- define "freeradius.validate.tls" -}}
{{- if and .Values.tls.enabled (not .Values.tls.autoGenerated) (not .Values.tls.certificatesSecret) (not .Values.tls.existingSecretName) (not (include "freeradius.tls.useCertManager" .)) -}}
freeradius: tls.enabled
    In order to enable RADSEC TLS (`tls.enabled: true`), you must also configure
    a certificate source. Set one of:
      - tls.autoGenerated: true            (chart auto-generates a leaf: via cert-manager when its API is present, else a self-signed genCA leaf)
      - tls.certificatesSecret: <name>     (BYO Secret already in the namespace)
      - tls.certManager.issuerRef.name: <issuer>   (cert-manager issues from your Issuer/ClusterIssuer; requires the cert-manager API)
{{- end -}}
{{- end -}}

{{/*
Validation message: metrics enabled but the RADIUS `status` virtual server is
disabled — the standalone exporter Deployment would have nothing to scrape.
*/}}
{{- define "freeradius.validate.metrics" -}}
{{- if and .Values.metrics.enabled (not .Values.sites.status.enabled) -}}
freeradius: metrics.enabled
    `metrics.enabled: true` requires `sites.status.enabled: true`.
    The bvantagelimited/freeradius_exporter Deployment reaches the RADIUS
    `status` virtual server through the cluster Service to scrape its
    counters — disabling the status site leaves the exporter with nothing
    to read, so the chart refuses to render this combination.
{{- end -}}
{{- end -}}

{{/*
Validation message: SQL backend selection must be coherent.

Rejects:
  - both bundled subcharts enabled at once,
  - a bundled subchart whose wire protocol doesn't match `modules.sql.dialect`,
  - `dialect: sqlite` with any bundled subchart enabled (sqlite is file-based),
  - `dialect: mysql|postgresql` with no subchart AND empty `externalDatabase.host`
    (no backend at all).
*/}}
{{- define "freeradius.validate.sql.backend" -}}
{{- if .Values.modules.sql.enabled -}}
{{- $dialect    := .Values.modules.sql.dialect -}}
{{- $mariadb    := .Values.mariadb.enabled -}}
{{- $postgresql := .Values.postgresql.enabled -}}
{{- if and $mariadb $postgresql -}}
freeradius: mariadb.enabled / postgresql.enabled
    Only one bundled database subchart may be enabled at a time. Set either
    `mariadb.enabled: true` (mysql dialect) or `postgresql.enabled: true`
    (postgresql dialect), not both.
{{- else if and (eq $dialect "sqlite") (or $mariadb $postgresql) -}}
freeradius: modules.sql.dialect=sqlite
    SQLite is a file-based engine — disable both bundled subcharts
    (`mariadb.enabled: false`, `postgresql.enabled: false`) and configure
    the SQLite file via `modules.sql.sqlite.*`.
{{- else if and $mariadb (ne $dialect "mysql") -}}
freeradius: mariadb.enabled
    `mariadb.enabled: true` requires `modules.sql.dialect: mysql`
    (currently `{{ $dialect }}`). The bundled MariaDB subchart only speaks
    the MySQL wire protocol.
{{- else if and $postgresql (ne $dialect "postgresql") -}}
freeradius: postgresql.enabled
    `postgresql.enabled: true` requires `modules.sql.dialect: postgresql`
    (currently `{{ $dialect }}`). The bundled PostgreSQL subchart only speaks
    the PostgreSQL wire protocol.
{{- else if and (ne $dialect "sqlite") (not $mariadb) (not $postgresql) (not .Values.externalDatabase.host) -}}
freeradius: modules.sql.dialect={{ $dialect }}
    No database backend is configured. Either enable a bundled subchart
    matching the dialect (`mariadb.enabled: true` for mysql,
    `postgresql.enabled: true` for postgresql) or point at an external
    database via `externalDatabase.host`. For a file-based backend, set
    `modules.sql.dialect: sqlite`.
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: REST module configuration coherence.

Rejects:
  - `rest.enabled: true` with empty `rest.connect_uri`,
  - `rest.auth != none` with no password source (no `password`, no
    `existingSecret`),
  - `rest.tls.enabled: true` with no cert source (no `auto_generated`, no
    `certificates_secret`),
  - `rest.auth` set to something other than the four known values.

Server-cert verification (`tls.check_cert*`) is independent of client-cert
material so it's not validated here — those flags work against the system
CA bundle when no `tls.*` material is mounted.
*/}}
{{- define "freeradius.validate.rest" -}}
{{- if .Values.modules.rest.enabled -}}
{{- $auth := .Values.modules.rest.auth -}}
{{- $allowedAuth := list "none" "basic" "digest" "bearer" -}}
{{- if not .Values.modules.rest.connect_uri -}}
freeradius: modules.rest.enabled
    `modules.rest.enabled: true` requires a non-empty
    `modules.rest.connect_uri` — rlm_rest has nothing to call without it.
{{- else if not (has $auth $allowedAuth) -}}
freeradius: modules.rest.auth
    `modules.rest.auth: {{ $auth }}` is not a recognised value. Allowed:
    `none`, `basic`, `digest`, `bearer`.
{{- else if and (ne $auth "none") (not .Values.modules.rest.password) (not .Values.modules.rest.existingSecret) -}}
freeradius: modules.rest.auth={{ $auth }}
    `modules.rest.auth: {{ $auth }}` requires a password source. Set
    one of:
      - modules.rest.password: <value>          (chart-managed Secret)
      - modules.rest.existingSecret: <name>     (BYO Secret already in the namespace)
{{- else if and .Values.modules.rest.tls.enabled (not .Values.modules.rest.tls.auto_generated) (not .Values.modules.rest.tls.certificates_secret) -}}
freeradius: modules.rest.tls.enabled
    `modules.rest.tls.enabled: true` requires a TLS material source.
    Set one of:
      - modules.rest.tls.auto_generated: true        (chart generates a self-signed leaf)
      - modules.rest.tls.certificates_secret: <name> (BYO Secret already in the namespace)
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: EAP module configuration coherence.

Rejects:
  - `eap.enabled: true` with no EAP method enabled,
  - `eap.defaultType` not among the ENABLED methods,
  - `eap.enabled: true` with no `tlsConfig` server-cert source (TLS-based EAP
    methods cannot start without one).
*/}}
{{- define "freeradius.validate.eap" -}}
{{- if .Values.modules.eap.enabled -}}
{{- $type := .Values.modules.eap.defaultType -}}
{{- $methods := .Values.modules.eap.methods -}}
{{- $outer := list -}}
{{- if has "tls" $methods -}}{{- $outer = append $outer "tls" -}}{{- end -}}
{{- if has "ttls" $methods -}}{{- $outer = append $outer "ttls" -}}{{- end -}}
{{- if eq (len $outer) 0 -}}
freeradius: modules.eap.methods
    `modules.eap.enabled: true` but no outer EAP method is enabled. Add at least
    one of `tls` / `ttls` to `modules.eap.methods`.
{{- else if not (has $type $outer) -}}
freeradius: modules.eap.defaultType
    `modules.eap.defaultType: {{ $type }}` must be one of the enabled outer
    methods ({{ join ", " $outer }}). Either change `defaultType` or add that
    method to `modules.eap.methods`.
{{- else if and (not .Values.modules.eap.tlsConfig.autoGenerated) (not .Values.modules.eap.tlsConfig.certificates_secret) -}}
freeradius: modules.eap.enabled
    `modules.eap.enabled: true` requires a TLS server-certificate source —
    the TLS-based EAP methods cannot start without one. Set one of:
      - modules.eap.tlsConfig.autoGenerated: true        (chart signs a leaf off its shared CA)
      - modules.eap.tlsConfig.certificates_secret: <name> (BYO Secret already in the namespace)
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: tls-cache virtual server preconditions. The site has no
value without (a) the EAP module to invoke it, and (b) a Redis backend so
resumption actually works across replicas — in-pod backends (rbtree) reduce
to the per-pod caveat we're trying to escape, so we hard-fail rather than
render something that ships a false promise.
*/}}
{{- define "freeradius.validate.tlsCache" -}}
{{- if .Values.sites.tlsCache.enabled -}}
{{- if not .Values.modules.eap.enabled -}}
freeradius: sites.tlsCache.enabled
    `sites.tlsCache.enabled: true` requires `modules.eap.enabled: true` —
    the tls-cache virtual server only makes sense as a backend for EAP TLS
    session resumption.
{{- else if and (not .Values.redis.enabled) (not .Values.modules.redis.server) -}}
freeradius: sites.tlsCache.enabled
    `sites.tlsCache.enabled: true` requires a Redis backend (cross-pod
    session resumption is the whole point — an in-pod cache defeats it).
    Either enable the bundled subchart (`redis.enabled: true`) or point
    `modules.redis.server` at an external Redis.
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation messages: per-instance checks for modules.cache.instances entries.
Same rules as the base cache module — driver must be one of the supported
backends and `update` must be non-empty (rlm_cache refuses to load without
at least one map).
*/}}
{{- define "freeradius.validate.cacheInstances" -}}
{{- $allowed := list "rbtree" "redis" "memcached" -}}
{{- range $name, $cfg := .Values.modules.cache.instances -}}
{{- if not (has $cfg.driver $allowed) }}
freeradius: modules.cache.instances.{{ $name }}.driver
    `modules.cache.instances.{{ $name }}.driver: {{ $cfg.driver }}` is not a recognised
    value. Allowed: `rbtree` (in-memory), `redis` (reuses the `modules.redis`
    connection), `memcached`.
{{- else if not (trim ($cfg.update | default "")) }}
freeradius: modules.cache.instances.{{ $name }}.update
    `modules.cache.instances.{{ $name }}` requires a non-empty `update` field.
    rlm_cache refuses to load without at least one map ("Must have an
    'update' section in order to cache anything"). Set `update` to one or
    more FreeRADIUS maps, e.g. `&reply: += &reply:`.
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Per-instance Keycloak validation. Iterates the effective instances map
(legacy top-level fields go through the deprecation shim in
`freeradius.keycloak.resolveInstances` before we see them). For each
instance:
  - `mode` must be one of lua / python,
  - `roleMapper` must be client / realm,
  - `tls.caCert` and `tls.existingSecret` are mutually exclusive,
  - `cache.enabled: true` requires a Redis backend (the chart standardises
    on Redis so the per-instance `keycloak_<name>_cache` shares state
    across replicas),
  - `realm` must be non-empty (centralised here — used to be duplicated
    across keycloak.yaml / keycloak-mapper-{lua,python}.yaml's `fail`
    calls; we now want all per-instance failures to surface at once),
  - instance name matches `^[a-z][a-z0-9_]*$` — required because the name
    is used as a Python module filename (`keycloak_<name>.py`, which is
    imported via `import keycloak_<name>`, forbidding hyphens) and as
    part of K8s resource names (DNS-1123 subdomain — lowercase + digits
    + dashes; we use the stricter Python-module rule which is also a
    valid DNS subdomain segment),
  - `extraEnvVars` must not shadow the per-instance env-var prefix the
    chart will emit (silent override bugs).
*/}}
{{- define "freeradius.validate.keycloakInstances" -}}
{{- if .Values.keycloak.enabled -}}
{{- $resolved := include "freeradius.keycloak.resolveInstances" . | fromYaml -}}
{{- $modeAllowed := list "lua" "python" -}}
{{- $roleMapperAllowed := list "client" "realm" -}}
{{- $nameRe := "^[a-z][a-z0-9_]*$" -}}
{{- $hasRedis := or .Values.redis.enabled .Values.modules.redis.server -}}
{{- $extraEnvNames := list -}}
{{- range $e := .Values.extraEnvVars -}}{{- $extraEnvNames = append $extraEnvNames $e.name -}}{{- end -}}
{{- range $name, $cfg := $resolved.instances }}
{{- if not (regexMatch $nameRe $name) }}
freeradius: keycloak.instances.{{ $name }}
    Instance name `{{ $name }}` must match `^[a-z][a-z0-9_]*$` — the name is
    used as a Python module filename (`keycloak_<name>.py`, imported via
    `import keycloak_<name>`, which forbids hyphens) and as a suffix on
    K8s resource names. Use lowercase letters, digits, and underscores;
    start with a letter.
{{- end -}}
{{- if not (has $cfg.mode $modeAllowed) }}
freeradius: keycloak.instances.{{ $name }}.mode
    `keycloak.instances.{{ $name }}.mode: {{ $cfg.mode }}` is not a recognised value.
    Allowed: `lua` (rlm_lua — custom image required, see [[reference_freeradius_3_2_8_bundled_modules]])
    or `python` (rlm_python3 — bundled).
{{- end -}}
{{- if not $cfg.realm }}
freeradius: keycloak.instances.{{ $name }}.realm
    `keycloak.instances.{{ $name }}.realm` is required — the OIDC token
    endpoint URL ends with `/realms/<realm>/protocol/openid-connect/token`
    and FreeRADIUS has no sensible default. Set it to the realm holding
    the users this instance authenticates.
{{- end -}}
{{- if not (has $cfg.roleMapper $roleMapperAllowed) }}
freeradius: keycloak.instances.{{ $name }}.roleMapper
    `keycloak.instances.{{ $name }}.roleMapper: {{ $cfg.roleMapper }}` is not a
    recognised value. Allowed: `client` (resource_access[clientId].roles)
    or `realm` (realm_access.roles).
{{- end -}}
{{- if and $cfg.tls $cfg.tls.caCert $cfg.tls.existingSecret }}
freeradius: keycloak.instances.{{ $name }}.tls
    `keycloak.instances.{{ $name }}.tls.caCert` and
    `keycloak.instances.{{ $name }}.tls.existingSecret` are mutually
    exclusive — set one or the other. Use `caCert` for an inline PEM
    rendered into a chart-managed Secret, or `existingSecret` to
    reference a Secret you manage outside this chart.
{{- end -}}
{{- if and $cfg.cache $cfg.cache.enabled (not $hasRedis) }}
freeradius: keycloak.instances.{{ $name }}.cache.enabled
    `keycloak.instances.{{ $name }}.cache.enabled: true` requires a Redis
    backend. Either enable the bundled subchart (`redis.enabled: true`)
    or point `modules.redis.server` at an external Redis. The chart
    standardises the per-instance `keycloak_cache_{{ $name }}` on Redis so
    state is shared across replicas.
{{- end -}}
{{- $roleAttr := default "Class" $cfg.roleAttribute -}}
{{- $groupAttr := default "Class" $cfg.groupAttribute -}}
{{- if and $cfg.roleMappings $cfg.groupMappings (eq $roleAttr $groupAttr) }}
freeradius: keycloak.instances.{{ $name }}.groupAttribute
    `keycloak.instances.{{ $name }}` defines both `roleMappings` and
    `groupMappings` but `roleAttribute` and `groupAttribute` resolve to
    the same control attribute (`{{ $roleAttr }}`). Roles and groups would
    accumulate in the same `&control:{{ $roleAttr }}[*]` list, and a
    Keycloak role name colliding with a Keycloak group name would
    falsely match either policy. Set `groupAttribute` to a different
    attribute (e.g. `Filter-Id`, `Tunnel-Private-Group-Id`) or fold the
    case into `attributeMappings`.
{{- end -}}
{{- range $i, $m := default list $cfg.groupMappings }}
{{- if not $m.group }}
freeradius: keycloak.instances.{{ $name }}.groupMappings[{{ $i }}].group
    Each `groupMappings` entry must set `group`. Use the Keycloak Group
    Membership client mapper output verbatim (full path, e.g.
    `/branch-a` or `/branch-a/hotspot`).
{{- end -}}
{{- end -}}
{{- range $i, $m := default list $cfg.attributeMappings }}
{{- if or (not $m.claim) (not $m.reply) }}
freeradius: keycloak.instances.{{ $name }}.attributeMappings[{{ $i }}]
    Each `attributeMappings` entry must set both `claim` (the JWT claim
    name, top-level only — dotted paths are NOT supported) and `reply`
    (the FreeRADIUS reply-attribute name to populate).
{{- end -}}
{{- end -}}
{{- range $i, $r := default list $cfg.require }}
{{- if not $r }}
freeradius: keycloak.instances.{{ $name }}.require[{{ $i }}]
    Each `require` entry must be a non-empty JWT claim name (top-level
    only). Truthy values pass; everything else rejects the request.
{{- end -}}
{{- end -}}
{{- if and $cfg.introspect (not $cfg.clientSecret) (not $cfg.existingSecret) }}
freeradius: keycloak.instances.{{ $name }}.introspect
    `keycloak.instances.{{ $name }}.introspect: true` requires a client
    secret — RFC 7662 introspection is HTTP-Basic-authenticated and
    Keycloak rejects unauthenticated introspect calls (401). Set
    `keycloak.instances.{{ $name }}.clientSecret` (inline, chart-managed
    Secret) or `keycloak.instances.{{ $name }}.existingSecret` (BYO).
{{- end -}}
{{- if and $cfg.refreshTokenCache (or (not $cfg.cache) (not $cfg.cache.enabled)) }}
freeradius: keycloak.instances.{{ $name }}.refreshTokenCache
    `keycloak.instances.{{ $name }}.refreshTokenCache: true` requires
    `keycloak.instances.{{ $name }}.cache.enabled: true` — the refresh
    flow runs on cache HIT (validates the cached refresh_token against
    Keycloak), and with the cache disabled there is no hit path to
    extend.
{{- end -}}
{{- $prefix := include "freeradius.keycloak.envVarPrefix" (dict "name" $name) -}}
{{- range $envName := $extraEnvNames -}}
{{- if hasPrefix $prefix $envName }}
freeradius: extraEnvVars
    `extraEnvVars` contains `{{ $envName }}`, which shadows the chart-emitted
    prefix `{{ $prefix }}*` for `keycloak.instances.{{ $name }}`. Pick a
    non-`FREERADIUS_KEYCLOAK_*` name to avoid silently overriding the
    chart's own injection.
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: every non-empty `clients.<x>.keycloak` must reference
an existing `keycloak.instances.<name>` entry, and the client must have a
non-empty `ipv4addr` (the dispatch chain in `sites/default` matches on
`Packet-Src-IP-Address`). Typo guard — a misspelled instance name in
`clients.foo.keycloak: typo` would otherwise render `keycloak_typo_authorize`
unlang that fails to load at runtime instead of at `helm install` time.
*/}}
{{- define "freeradius.validate.keycloakClientBindings" -}}
{{- if .Values.keycloak.enabled -}}
{{- $resolved := include "freeradius.keycloak.resolveInstances" . | fromYaml -}}
{{- range $clientName, $client := .Values.clients -}}
{{- if and (kindIs "map" $client) $client.keycloak -}}
{{- if not (hasKey $resolved.instances $client.keycloak) }}
freeradius: clients.{{ $clientName }}.keycloak
    `clients.{{ $clientName }}.keycloak: {{ $client.keycloak }}` references
    an undefined instance — add it under `keycloak.instances.{{ $client.keycloak }}`
    or fix the typo. Defined instances: {{ join ", " (keys $resolved.instances) }}.
{{- else if not $client.ipv4addr }}
freeradius: clients.{{ $clientName }}.keycloak
    `clients.{{ $clientName }}.keycloak: {{ $client.keycloak }}` requires a
    non-empty `clients.{{ $clientName }}.ipv4addr` — the dispatch chain in
    `sites/default` matches on `Packet-Src-IP-Address` and has nothing to
    bind against.
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: cache module driver must be one of the supported backends.
*/}}
{{- define "freeradius.validate.cache" -}}
{{- if .Values.modules.cache.enabled -}}
{{- $driver := .Values.modules.cache.driver -}}
{{- $allowed := list "rbtree" "redis" "memcached" -}}
{{- if not (has $driver $allowed) -}}
freeradius: modules.cache.driver
    `modules.cache.driver: {{ $driver }}` is not a recognised value. Allowed:
    `rbtree` (in-memory), `redis` (reuses the `modules.redis` connection), `memcached`.
{{- else if not (trim (.Values.modules.cache.update | default "")) -}}
freeradius: modules.cache.update
    `modules.cache.enabled: true` requires a non-empty `modules.cache.update`.
    rlm_cache refuses to load without at least one map ("Must have an 'update'
    section in order to cache anything"). Set `modules.cache.update` to one or
    more FreeRADIUS maps, e.g. `&reply: += &reply:`.
{{- end -}}
{{- end -}}
{{- end -}}
