{{- /*
(c) 2026 Firmansyah Nainggolan <firmansyah@nainggolan.id>. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
Hard-validation aggregator. Each `freeradius.validate.<area>` helper below
returns a non-empty string when its precondition is violated, otherwise the
empty string. This template gathers all of them, drops the empty entries,
and calls `fail` when anything remains so `helm install` / `helm upgrade` /
`helm template` reject the misconfigured release before any resource is
applied.

Included from `templates/NOTES.txt` (Helm renders NOTES.txt as part of the
install path, so a `fail` here aborts the operation).
*/}}
{{- define "freeradius.validate" -}}
{{- $messages := list -}}
{{- $messages = append $messages (include "freeradius.validate.tls" .) -}}
{{- $messages = append $messages (include "freeradius.validate.metrics" .) -}}
{{- $messages = append $messages (include "freeradius.validate.sql.backend" .) -}}
{{- $messages = append $messages (include "freeradius.validate.rest" .) -}}
{{- $messages = append $messages (include "freeradius.validate.eap" .) -}}
{{- $messages := without $messages "" -}}
{{- $message := join "\n" $messages -}}
{{- if $message -}}
{{- printf "\nVALUES VALIDATION:\n%s" $message | fail -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: RADSEC enabled but no cert source configured.
*/}}
{{- define "freeradius.validate.tls" -}}
{{- if and .Values.tls.enabled (not .Values.tls.autoGenerated) (not .Values.tls.certificatesSecret) (not .Values.tls.existingSecretName) (not .Values.tls.certManager.create) -}}
freeradius: tls.enabled
    In order to enable RADSEC TLS (`tls.enabled: true`), you must also configure
    a certificate source. Set one of:
      - tls.autoGenerated: true            (chart generates a self-signed leaf)
      - tls.certificatesSecret: <name>     (BYO Secret already in the namespace)
      - tls.certManager.create: true       (cert-manager issues the Certificate)
{{- end -}}
{{- end -}}

{{/*
Validation message: metrics enabled but the RADIUS `status` virtual server is
disabled — the standalone exporter Deployment would have nothing to scrape.
*/}}
{{- define "freeradius.validate.metrics" -}}
{{- if and .Values.metrics.enabled (not .Values.sites.status.enabled) -}}
freeradius: metrics.enabled
    `metrics.enabled: true` requires `sites.status.enabled: true`.
    The bvantagelimited/freeradius_exporter Deployment reaches the RADIUS
    `status` virtual server through the cluster Service to scrape its
    counters — disabling the status site leaves the exporter with nothing
    to read, so the chart refuses to render this combination.
{{- end -}}
{{- end -}}

{{/*
Validation message: SQL backend selection must be coherent.

Rejects:
  - both bundled subcharts enabled at once,
  - a bundled subchart whose wire protocol doesn't match `modules.sql.dialect`,
  - `dialect: sqlite` with any bundled subchart enabled (sqlite is file-based),
  - `dialect: mysql|postgresql` with no subchart AND empty `externalDatabase.host`
    (no backend at all).
*/}}
{{- define "freeradius.validate.sql.backend" -}}
{{- if .Values.modules.sql.enabled -}}
{{- $dialect    := .Values.modules.sql.dialect -}}
{{- $mariadb    := .Values.mariadb.enabled -}}
{{- $postgresql := .Values.postgresql.enabled -}}
{{- if and $mariadb $postgresql -}}
freeradius: mariadb.enabled / postgresql.enabled
    Only one bundled database subchart may be enabled at a time. Set either
    `mariadb.enabled: true` (mysql dialect) or `postgresql.enabled: true`
    (postgresql dialect), not both.
{{- else if and (eq $dialect "sqlite") (or $mariadb $postgresql) -}}
freeradius: modules.sql.dialect=sqlite
    SQLite is a file-based engine — disable both bundled subcharts
    (`mariadb.enabled: false`, `postgresql.enabled: false`) and configure
    the SQLite file via `modules.sql.sqlite.*`.
{{- else if and $mariadb (ne $dialect "mysql") -}}
freeradius: mariadb.enabled
    `mariadb.enabled: true` requires `modules.sql.dialect: mysql`
    (currently `{{ $dialect }}`). The bundled MariaDB subchart only speaks
    the MySQL wire protocol.
{{- else if and $postgresql (ne $dialect "postgresql") -}}
freeradius: postgresql.enabled
    `postgresql.enabled: true` requires `modules.sql.dialect: postgresql`
    (currently `{{ $dialect }}`). The bundled PostgreSQL subchart only speaks
    the PostgreSQL wire protocol.
{{- else if and (ne $dialect "sqlite") (not $mariadb) (not $postgresql) (not .Values.externalDatabase.host) -}}
freeradius: modules.sql.dialect={{ $dialect }}
    No database backend is configured. Either enable a bundled subchart
    matching the dialect (`mariadb.enabled: true` for mysql,
    `postgresql.enabled: true` for postgresql) or point at an external
    database via `externalDatabase.host`. For a file-based backend, set
    `modules.sql.dialect: sqlite`.
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: REST module configuration coherence.

Rejects:
  - `rest.enabled: true` with empty `rest.connect_uri`,
  - `rest.auth != none` with no password source (no `password`, no
    `existingSecret`),
  - `rest.tls.enabled: true` with no cert source (no `auto_generated`, no
    `certificates_secret`),
  - `rest.auth` set to something other than the four known values.

Server-cert verification (`tls.check_cert*`) is independent of client-cert
material so it's not validated here — those flags work against the system
CA bundle when no `tls.*` material is mounted.
*/}}
{{- define "freeradius.validate.rest" -}}
{{- if .Values.modules.rest.enabled -}}
{{- $auth := .Values.modules.rest.auth -}}
{{- $allowedAuth := list "none" "basic" "digest" "bearer" -}}
{{- if not .Values.modules.rest.connect_uri -}}
freeradius: modules.rest.enabled
    `modules.rest.enabled: true` requires a non-empty
    `modules.rest.connect_uri` — rlm_rest has nothing to call without it.
{{- else if not (has $auth $allowedAuth) -}}
freeradius: modules.rest.auth
    `modules.rest.auth: {{ $auth }}` is not a recognised value. Allowed:
    `none`, `basic`, `digest`, `bearer`.
{{- else if and (ne $auth "none") (not .Values.modules.rest.password) (not .Values.modules.rest.existingSecret) -}}
freeradius: modules.rest.auth={{ $auth }}
    `modules.rest.auth: {{ $auth }}` requires a password source. Set
    one of:
      - modules.rest.password: <value>          (chart-managed Secret)
      - modules.rest.existingSecret: <name>     (BYO Secret already in the namespace)
{{- else if and .Values.modules.rest.tls.enabled (not .Values.modules.rest.tls.auto_generated) (not .Values.modules.rest.tls.certificates_secret) -}}
freeradius: modules.rest.tls.enabled
    `modules.rest.tls.enabled: true` requires a TLS material source.
    Set one of:
      - modules.rest.tls.auto_generated: true        (chart generates a self-signed leaf)
      - modules.rest.tls.certificates_secret: <name> (BYO Secret already in the namespace)
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Validation message: EAP module configuration coherence.

Rejects:
  - `eap.enabled: true` with no EAP method enabled,
  - `eap.defaultType` not among the ENABLED methods,
  - `eap.enabled: true` with no `tlsConfig` server-cert source (TLS-based EAP
    methods cannot start without one).
*/}}
{{- define "freeradius.validate.eap" -}}
{{- if .Values.modules.eap.enabled -}}
{{- $type := .Values.modules.eap.defaultType -}}
{{- $methods := .Values.modules.eap.methods -}}
{{- $outer := list -}}
{{- if has "tls" $methods -}}{{- $outer = append $outer "tls" -}}{{- end -}}
{{- if has "ttls" $methods -}}{{- $outer = append $outer "ttls" -}}{{- end -}}
{{- if eq (len $outer) 0 -}}
freeradius: modules.eap.methods
    `modules.eap.enabled: true` but no outer EAP method is enabled. Add at least
    one of `tls` / `ttls` to `modules.eap.methods`.
{{- else if not (has $type $outer) -}}
freeradius: modules.eap.defaultType
    `modules.eap.defaultType: {{ $type }}` must be one of the enabled outer
    methods ({{ join ", " $outer }}). Either change `defaultType` or add that
    method to `modules.eap.methods`.
{{- else if and (not .Values.modules.eap.tlsConfig.autoGenerated) (not .Values.modules.eap.tlsConfig.certificates_secret) -}}
freeradius: modules.eap.enabled
    `modules.eap.enabled: true` requires a TLS server-certificate source —
    the TLS-based EAP methods cannot start without one. Set one of:
      - modules.eap.tlsConfig.autoGenerated: true        (chart signs a leaf off its shared CA)
      - modules.eap.tlsConfig.certificates_secret: <name> (BYO Secret already in the namespace)
{{- end -}}
{{- end -}}
{{- end -}}
